CREATE TABLE CLIENT_MASTER (
    CLIENTNO VARCHAR(6) CONSTRAINT pk_clientno PRIMARY KEY CHECK (CLIENTNO LIKE 'C%'),
    NAME VARCHAR(20) NOT NULL,
    ADDRESS1 VARCHAR(30),
    ADDRESS2 VARCHAR(30),
    CITY VARCHAR(15),
    PINCODE NUMERIC(8),
    STATE VARCHAR(15),
    BALDUE NUMERIC(10,2)
);

INSERT INTO Client_Master VALUES 
('C00001', 'Ivan Bayross', 'ABC House','Gandhi Street','Mumbai', 400054, 'Maharashtra', 15000),
('C00002','Amit Antony','XYZ House','Tirupathi Nagar','Chennai',506767,'Tamilnadu',20000);

CREATE TABLE PRODUCT_MASTER (
  PRODUCTNO VARCHAR(6) CONSTRAINT PK_PRODUCTNO PRIMARY KEY CONSTRAINT CHK_PRODUCTNO CHECK (PRODUCTNO LIKE 'P%'),
  DESCRIPTION VARCHAR(15) NOT NULL,
  PROFITPERC NUMERIC(4,2) NOT NULL,
  UNITMEASURE VARCHAR(10) NOT NULL,
  QTYONHAND NUMERIC(8) NOT NULL,
  REORDERLVL NUMERIC(8) NOT NULL,
  SELLPRICE NUMERIC(8,2) CONSTRAINT CHK_SELLPRICE CHECK (SELLPRICE <> 0) NOT NULL,
  COSTPRICE NUMERIC(8,2) CONSTRAINT CHK_COSTPRICE CHECK (COSTPRICE <> 0) NOT NULL
);

INSERT INTO Product_Master VALUES 
('P00001', 'T-Shirts', 5, 'Piece', 200, 50, 350, 250),
('P00002','Jeans',3,'Piece',100,55,1000,1500),
('P00003','Kurti',6,'Piece',110,30,800,850);

CREATE TABLE SALESMAN_MASTER (
    SALESMANNO varchar(6) CONSTRAINT pk_salesmanno PRIMARY KEY CHECK (SALESMANNO LIKE 'S%'),
    SALESMANNAME varchar(20) NOT NULL,
    ADDRESS1 varchar(30) NOT NULL,
    ADDRESS2 varchar(30),
    CITY varchar(20),
    PINCODE numeric(8),
    STATE varchar(20),
    SALAMT numeric(8,2) NOT NULL CHECK (SALAMT <> 0),
    TGTTOGET numeric(6,2) NOT NULL,
    YTDSALES numeric(6,2) NOT NULL,
    REMARKS varchar(60)
);

INSERT INTO Salesman_Master VALUES 
('S00001', 'Aman', 'A/14', 'Worli', 'Mumbai', 400002, 'Maharashtra', 3000, 100, 50, 'Good'),
('S00002', 'Neerav', 'B/16', 'Alandur', 'Chennai', 509997, 'tamilnadu', 3500, 50, 55, 'Average'), 
('S00003', 'Daksha', 'A/09', 'Pampady', 'Kottayam', 686589, 'Kerala', 1000, 200, 80, 'Excellent');

CREATE TABLE SALES_ORDER (
    ORDERNO VARCHAR(6) CONSTRAINT pk_sales_order PRIMARY KEY CHECK (ORDERNO LIKE 'O%'),
    CLIENTNO VARCHAR(6) CONSTRAINT fk_sales_order_client REFERENCES CLIENT_MASTER (CLIENTNO),
    ORDERDATE DATE,
    DELYADDR VARCHAR(25),
    SALESMANNO VARCHAR(6) CONSTRAINT fk_sales_order_salesman REFERENCES SALESMAN_MASTER (SALESMANNO),
    DELYTYPE CHAR(1) CHECK (DELYTYPE IN ('P', 'F')),
    BILLEDYN CHAR(1) CHECK (BILLEDYN IN ('Y', 'N')),
    DELYDATE DATE,
    ORDERSTATUS VARCHAR(10) CHECK (ORDERSTATUS IN ('In Process', 'Fulfilled', 'Backorder', 'Cancelled'))
);

select * from SALES_ORDER;
/*INSERT INTO Sales_Order VALUES
('O19001', 'C00001','12-june-22', 'ABC House', 'S00002','P','Y','20-june-22', 'In Process'),
('O19002', 'C00003','21-april-02', 'DEF House', 'S00003','F', 'Y', '30-april-02', 'Cancelled'),
('O19003', 'C00002','09-january-23', 'XYZ House', 'S00001','P', 'Y', '15-october-23', 'Backorder'); */
 INSERT INTO Sales_Order (OrderNo, OrderDate, ClientNo, DelyType, BilledYn, SalesmanNo, DelyDate, OrderStatus) 
 VALUES('O19001', '12-june-02', 'C00001', 'F', 'N', 'S00001', '20-july-02', 'In Process');


CREATE TABLE SALES_ORDER_DETAILS (
  ORDERNO varchar(6),
  PRODUCTNO varchar(6),
  QTYORDERED numeric(8),
  QTYDISP numeric(8),
  PRODUCTRATE numeric(10,2),
  CONSTRAINT PK_SALES_ORDER_DETAILS PRIMARY KEY (ORDERNO, PRODUCTNO),
  CONSTRAINT FK_SALES_ORDER FOREIGN KEY (ORDERNO) REFERENCES SALES_ORDER(ORDERNO),
  CONSTRAINT FK_PRODUCT_MASTER FOREIGN KEY (PRODUCTNO) REFERENCES PRODUCT_MASTER(PRODUCTNO)
);

INSERT INTO Sales_Order_Details (OrderNo, ProductNo, QtyOrdered, QtyDisp, ProductRate) VALUES('O19001', 'P00001', 4, 4, 525); 



